project_id: 365295
api_token: CROWDIN_DAYJS_PROJECT_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  [
    {
      source: "/docs/**/*.md",
      translation: "/website/translated_docs/%locale%/**/%original_file_name%",
    },
    {
      source: "/website/i18n/en.json",
      translation: "/website/i18n/%locale%.json",
    },
  ]
