name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name github-actions[bot] 
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "machine github.com login github-actions[bot] password ${GITHUB_TOKEN}" > ~/.netrc
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: 'website'
      - name: Write English translations
        run: pnpm run write-translations
        working-directory: 'website'
      - name: Upload && download translations
        env:
          CROWDIN_DAYJS_PROJECT_API_KEY: ${{ secrets.CROWDIN_DAYJS_PROJECT_API_KEY }}
          CROWDIN_DAYJS_PROJECT_ID: ${{ secrets.CROWDIN_DAYJS_PROJECT_ID }}
        run: |
          pnpm run crowdin-upload
          pnpm run crowdin-download
        working-directory: 'website'
      - name: Publish to GitHub Pages
        run: GIT_USER=github-actions[bot] pnpm run publish-gh-pages
        working-directory: 'website'
